version: "3.0"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres

    volumes:
      - postgres-db:/data/postgres
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pmluque@sia.es
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "99:80"
    depends_on:
      - postgres

volumes:
  postgres-db:
    driver: local
